fix: update supabase to resolve RealtimeSubscription error
supabase/supabase-flutter pull request #58
Opened 2022-01-08 19:14 UTC by MisterJimson

Resolves #55 

## What kind of change does this PR introduce?

Bug fix for #55 

## What is the current behavior?
Exception is throw when using Realtime

Please link any relevant issues here.
See #55 and https://github.com/supabase-community/supabase-dart/issues/64

## What is the new behavior?

No longer throws an error.

Feel free to include screenshots if it includes visual changes.

## Additional context

The current stable Dart SDK has new lints built in around imports. Those need to be addressed for checks to passed, so they were also done in this PR.

2022-01-11 12:44 UTC, bdlukaa commented on pubspec.yaml
> +  supabase: ^0.2.10
Latest version is 0.2.11

https://pub.dev/packages/supabase/changelog

2022-01-11 12:44 UTC, bdlukaa requested changes

2022-01-11 12:44 UTC, bdlukaa commented on pubspec.yaml
> +  supabase: ^0.2.10
```suggestion
  supabase: ^0.2.11
```

2022-01-13 18:23 UTC, MisterJimson commented on pubspec.yaml
> -  supabase: ^0.2.7
Do I need to setup a script to update this PR every time a version is released lol?

2022-01-13 18:44 UTC, KirioXX commented on pubspec.yaml
> -  supabase: ^0.2.7
Sorry, probably needed a bit more context 😅. 
There was a small but significant bug in version 0.2.11 that was fixed with version 0.2.12.

@bdlukaa can this be merged and released?

2022-01-13 18:46 UTC, MisterJimson commented on pubspec.yaml
> -  supabase: ^0.2.7
Haha no worries. Ill bump it.

2022-01-14 02:30 UTC, phamhieu commented
merged into #61

2022-01-14 02:30 UTC, closed without merging