feat!(realtime_client): Provide better typing for realtime presence.
supabase/supabase-flutter pull request #747
Opened 2023-12-01 04:41 UTC by dshukertjr

## What kind of change does this PR introduce?

Currently, a lot of data passed around the realtime presence feature relies on `Map`. Some of them have very weird typing using Map such as the return type of `channel.presenceState()` being `Map<String, List<Presence>>`. This PR aims to add better typing for better developer experiences. 

## What is the current behavior?
`payload` in callback is `Map<String, dynamic>` when the SDK knows a bit more about what data could come in.

Also `channel.presenceState()` has `Map<String, List<Presence>>` as its return type;

```dart
    channel = supabase
        .channel('name')
        .onPresence(
          event: PresenceEvent.sync,
          callback: (payload) {
            print(payload); // `payload` is type `Map<String, dynamic>`
            print(channel.presenceState()); // prints `{'UUID': [Presence(key: 'presenceKey', payload: {'my': 'payload'})]}
          },
        ).subscribe();
````

## What is the new behavior?

Now `onPresence` takes a generic that extends a newly created `RealtimePresencePayload` object. 

There are three types for the payload `PresenceSyncPayload`, `PresenceJoinPayload`, and `PresenceLeavePayload`, and the users are required to add the generics to use presence. 

```dart
channel = supabase
    .channel('name')
    .onPresence<PresenceSyncPayload>(
      event: PresenceEvent.sync,
      callback: (PresenceSyncPayload payload) {
        print(payload);
        print(channel.presenceState()); // returns type `List<SinglePresenceState>`
      },
    )
    .onPresence<PresenceJoinPayload>(
      event: PresenceEvent.join,
      callback: (PresenceJoinPayload payload) {
        payload.event;
        payload.key;
        payload.currentPresences;
        payload.newPresences;
      },
    )
    .onPresence<PresenceLeavePayload>(
      event: PresenceEvent.leave,
      callback: (PresenceLeavePayload payload) {
        payload.event;
        payload.key;
        payload.currentPresences;
        payload.leftPresences;
      },
    )
    .subscribe();
```

Also `channel.presenceState()` now returns type `List<SinglePresenceState>`, which should be more intuitive to the users. 

Before, the returned type for `channel.resenceState()` was a Map with the key being a server generate UUID `key`, and the value was the list of `Presence`. 

Now, instead of using Map, we just return a `List` of `SinglePresenceState` instances, which contains the `key` and the `presences` object.

2023-12-01 13:59 UTC, dshukertjr commented
I think this will be the last realtime updates.

2023-12-03 22:38 UTC, Vinzent03 requested changes
From what I see, we have no tests for `onPresence()`. There are only a few realtime tests, but I think this method should be added.

2023-12-04 05:28 UTC, dshukertjr commented on packages/realtime_client/lib/src/types.dart
> +  /// By default the realtime server generates a UUIDv1 key for each client.
Do you mean like this?
```suggestion
  /// 
  /// By default the realtime server generates a UUIDv1 key for each client.
```

2023-12-04 10:46 UTC, dshukertjr commented on packages/realtime_client/lib/src/realtime_channel.dart
>      required PresenceEvent event,
Sounds good! Will make the edit right now!

2023-12-04 23:07 UTC, Vinzent03 approved these changes

2023-12-05 00:47 UTC, merged