chore:
supabase/supabase-flutter pull request #787
Opened 2024-01-05 11:03 UTC by dshukertjr

## What kind of change does this PR introduce?

- Remove the sample code from top level README.md
- Add some description on how to add the package locally using melos
- Remove the unused release github actions. - Currently exploring [Melos action](https://github.com/marketplace/actions/melos-action) to see if we can truly automate the release process. 
- Add a Github action to check if PR title has the correct format.

2024-01-07 19:20 UTC, Vinzent03 requested changes
So to understand the current publish process, the release prs only increase the version and add changelog, you pull and manually release each package?

2024-01-07 19:20 UTC, Vinzent03 commented on README.md
> +- Add the target package to your `pubspec.yaml` file specifying the path.
What about adding a pubspec excerpt example here
```yml
supabase_flutter:
  path: <your-path-to-the-supabase_flutter-directory>
```

2024-01-07 19:20 UTC, Vinzent03 commented on README.md
> +- Clone this repo
I think we can add the simple command to install melos here as well:
`dart pub global activate melos`

2024-01-08 02:52 UTC, dshukertjr commented
>So to understand the current publish process, the release prs only increase the version and add changelog, you pull and manually release each package?

Yes, I do publish the packages manually using Melos currently. 
Currently it looks like this:

1. Create `chore/publish` branch from `main`
2. Run `melos version`, which bumps the package version number, adds changelogs, updates version.dart files, and creates a Git tag.
3. Create a PR. 
4. After the PR is merged, pull `main` and run `melos publish`, which publishes all the updated packages.

2024-01-08 07:45 UTC, Vinzent03 approved these changes

2024-01-08 08:13 UTC, merged