feat: Add `detectSessionInUrl` option to optionally disable deep link observer.
supabase/supabase-flutter pull request #848
Opened 2024-02-29 00:28 UTC by dshukertjr

## What kind of change does this PR introduce?

js client has [detectSessionInUrl](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L100) option to optionally disable obtaining sessions from URL. This PR adds the same parameter, but renames the end to `uri` from `url`.

Closes https://github.com/supabase/supabase-flutter/issues/847

We've had the following two PRs related to this, but 
https://github.com/supabase/supabase-flutter/pull/669
https://github.com/supabase/supabase-flutter/pull/605

2024-02-29 01:08 UTC, gadfly361 commented
@dshukertjr thank you for this PR 🙏

2024-02-29 11:48 UTC, bdlukaa approved these changes

2024-02-29 12:51 UTC, Vinzent03 requested changes
I would change `_stopDeeplinkObserver()` as well as it prints now `***** SupabaseDeepLinkingMixin stopAuthObserver` even though no subscription exists.

2024-02-29 12:51 UTC, Vinzent03 commented on packages/supabase_flutter/lib/src/flutter_go_true_client_options.dart
> +  /// If true, the client will start the deep link observer and obtain sessions
Some word is missing in this sentence. Like `when` at the end?

2024-02-29 12:51 UTC, Vinzent03 commented on packages/supabase_flutter/lib/src/flutter_go_true_client_options.dart
> +    bool? detectSessionInUrl,
Change `detectSessionInUrl` to `detectSessionInUri`

2024-03-01 02:27 UTC, dshukertjr commented on packages/supabase_flutter/lib/src/flutter_go_true_client_options.dart
>      dynamic pkceAsyncStorage,
Yeah, let me add that too!

2024-03-01 07:36 UTC, Vinzent03 approved these changes

2024-03-01 09:00 UTC, merged