fix: match does not accept null value
supabase/supabase-flutter pull request #919
Opened 2024-05-07 11:57 UTC by dshukertjr

## What kind of change does this PR introduce?

Fixes https://github.com/supabase/supabase-flutter/issues/917

## What is the current behavior?

Currently, users can pass `null` to `match()` filter. 

## What is the new behavior?

Users will not be able to pass `null` to `match()`.

2024-05-07 12:47 UTC, bdlukaa approved these changes

2024-05-07 15:01 UTC, Vinzent03 commented
But the type of a map may be easily `Map<dynamic,dynamic>` despite having no null entries. So a working code might break now. I would prefer to note it in the documentation and use an assert over the actual values instead.

2024-05-07 15:29 UTC, dshukertjr commented
Fair enough.

2024-05-07 18:26 UTC, Vinzent03 requested changes

2024-05-07 18:26 UTC, Vinzent03 commented on packages/postgrest/lib/src/postgrest_filter_builder.dart
> +    query.forEach((k, v) => url = appendSearchParams(k, 'eq.$v', url));
Might be good to undo this.
```suggestion
    query.forEach((k, v) => url = appendSearchParams('$k', 'eq.$v', url));
```

2024-05-07 21:10 UTC, bdlukaa commented
I like the first proposed solution better. It gives the developers type-safety, causing less hassle. It might be good to have this shipped in the next major release.

2024-05-08 03:55 UTC, dshukertjr commented
>I like the first proposed solution better. It gives the developers type-safety, causing less hassle.

I like it too. I think sometimes we try to be a bit too picky about what defines a breaking change. I feel like the world does revolve around these minor "technically breaking changes" being shipped as a bug fix all the time. Flutter itself ships "breaking changes" without bumping the major versions all the time, and as long as it's under moderation, I don't think we should hesitate to ship these changes. 

I'd say we just ship it with the original change.

2024-05-09 08:37 UTC, Vinzent03 approved these changes
I don't think you can compare Flutter breaking changes with package breaking changes. Packages should use semver, Flutter doesn't.
I'm pretty sure three are code basis, which throw a static analysis error now, which definitely is a breaking change. But sure, our other bug fixes may sometimes be more breaking, and they  don't even show up when compiling.
I wouldn't make this breaking change, but you decide.

2024-05-13 09:10 UTC, merged