feat(realtime_client): Add support for authorized realtime channels with broadcast and presence.
supabase/supabase-flutter pull request #970
Opened 2024-07-10 05:27 UTC by dshukertjr

## What kind of change does this PR introduce?

Adds support for authorization on broadcast and presence

## What is the current behavior?

Authorization is not supported on broadcast or presence allowing anyone to listen to its messages. 

## What is the new behavior?

Realtime channel created with `private: true` will respect RLS. Read more on the [official docs](https://supabase.com/docs/guides/realtime/authorization).

```dart
channel = supabase.channel(
  'my_channel',
  opts: const RealtimeChannelConfig(private: true),
);
```

2024-07-10 22:06 UTC, Vinzent03 requested changes

2024-07-10 22:06 UTC, Vinzent03 commented on packages/realtime_client/lib/src/realtime_channel.dart
> +  late final bool _private;
I think this attribute should be documented as well like in `RealtimeChannelConfig`

2024-07-11 12:48 UTC, Vinzent03 approved these changes

2024-07-12 02:45 UTC, dshukertjr commented on packages/realtime_client/lib/src/realtime_channel.dart
> +            socket.accessToken != null ? 'Bearer ${socket.accessToken}' : '',
Thanks for the tidy up!

2024-07-12 02:45 UTC, merged