Upgrade `web_socket_channel` for supporting `web: ^1.0.0` and therefore WASM compilation on web
supabase/supabase-flutter pull request #992
Opened 2024-07-29 07:16 UTC by geoextra

## What kind of change does this PR introduce?

Upgrade the  `web_socket_channel` to `^3.0.1` which mostly serves as an upgrade path for the transitive `web` dependency which otherwise causes `web_socket_channel` to downgrade and prevent WASM support on the web platform.

## What is the current behavior?

When having `supabase` or `supabase_flutter` as a project dependeny while relying on `web: ^1.0.0` the  `web_socket_channel` dependeny would downgrade and WASM compilation isn't possible anymore.

## What is the new behavior?

This behavior seems to be migrated.

## Additional context

The breaking changes don't affect the codebase. Tests passed locally. Additionally, one linting error got fixed.

2024-07-29 07:44 UTC, dshukertjr requested changes
Thanks for this PR! 

Can we update the `web_socket_channel` dependencies to `'>=2.3.0 <4.0.0'` so that this doesn't become a breaking change?

2024-07-29 16:44 UTC, geoextra commented
Seems like I was a bit too fast with upgrading the linting dependecy which are not compatible with Dart version < 3.1 and fails tests, I will adjust to a non-breaking version.

2024-07-30 00:40 UTC, dshukertjr commented on packages/supabase/lib/src/auth_user.dart
> +    required Map<String, dynamic> super.userMetadata,
```suggestion
    required super.userMetadata,
```

2024-07-30 00:41 UTC, dshukertjr commented on packages/supabase/pubspec.yaml
> +  web_socket_channel: '>=2.3.0 <4.0.0'
```suggestion
  web_socket_channel: '>=2.2.0 <4.0.0'
```

2024-07-30 02:09 UTC, dshukertjr commented on packages/supabase/lib/src/supabase_query_builder.dart
> +    required String super.schema,
```suggestion
    super.headers = const {},
    required super.schema,
```

2024-07-30 02:09 UTC, dshukertjr commented on packages/supabase/lib/src/supabase_query_builder.dart
> +    required YAJsonIsolate super.isolate,
```suggestion
    required super.isolate,
```

2024-07-30 02:10 UTC, dshukertjr commented on packages/supabase/lib/src/auth_user.dart
> +    required String super.updatedAt,
```suggestion
    required super.role,
    required super.updatedAt,
```

2024-07-30 02:33 UTC, dshukertjr approved these changes
Thanks for this update! This will be included in the next release in a few days!

2024-07-30 02:33 UTC, merged